## suspicious
# An R Packages based on Quartz's Guide to Bad Data
# Contains functions to check for common dataset problems 



check_frame_dimensions<-function(df){
  # Spreadsheet has 65536 rows
  # The maximum number of rows an old-fashioned Excel spreadsheet was allowed to have was 65,536. 
  # If you receive a dataset with that number of rows you have almost certainly been given 
  # truncated data. Go back and ask for the rest. Newer versions of Excel allowed for 1,048,576 
  # rows, so it's less likely you'll be working with data that hits the limit.
  # 
  # Spreadsheet has 255 columns
  # Apple's Numbers app can only handle spreadsheets with 255 columns, and the app will 
  # truncate files that have more columns without warning the user. If you receive a dataset 
  # with exactly 255 columns, ask if the file was ever opened or converted with Numbers.
  
  if (nrow(df) == 65536 | 1048576) {
    print("your number of rows may be problematic")
    } else if (ncol(df) == 255){
      print("your number of columns may be problematic")
      } else {
        print("Data frame dimensions -- no problems detected") 
      }
  }

check_numeric<-function(x){
  numlist<-c(65535,255,2147483647,4294967295,99999,00000,9999,0000,999,000)
  if (x %in% numlist){
    return("Some of the numbers in this list look suspicious")
  } else {
    return("No suspicious numbers detected")
  }
}

check_telephone<-function(x){
  # 555-
}

check_dates<-function(x){
  # datelist<-c(1970-01-01T00:00:00Z, 1969-12-31T23:59:59Z, January 1st, 1900, January 1st, 1904) #Common start dates 
}

check_locations<-function(x){
  # loclist<-c(0°00'00.0"N+0°00'00.0"E, 0°N 0°E)
}

check_zips<-function(x){
  ziplist<-c(12345,90210) #Schenectady, NY and Beverly Hills, CA
  if (x %in% zipist) {
    print("Check your zip codes--are you in Schenectady or Beverly Hills?")
  } else {
    print("No suspicious Zip Codes Detected")
  }
}


check_benford<-function(df){ 
  # Benford's Law fails
  # Benford's Law is a theory which states that small digits (1, 2, 3) appear at the beginning of numbers much more 
  # frequently than large digits (7, 8, 9). In theory Benford's Law can be used to detect anomalies in accounting 
  # practices or election results, though in practice it can easily be misapplied. If you suspect a dataset has 
  # been created or modified to deceive, Benford's Law is an excellent first test, but you should always verify 
  # your results with an expert before concluding your data have been manipulated.
  # 
  # convert all numerics to strings, do a strsplit to remove all but first digit
  # then rank the first digits by frequency and compare to function generated by
  # Benford's Law
}
